Repository Trip-Transfer-Trade/backend, pull requests merged in 2025-03, with the labels that each got.

#38 [Fix/#8 refactor exchange] 환전하기 리팩토링
  module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrency.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeHistory.java
  module-trip/src/main/java/com/example/module_trip/account/AccountController.java
  module-trip/src/main/java/com/example/module_trip/account/AccountRepository.java
  module-trip/src/main/java/com/example/module_trip/account/AccountResponseDTO.java
  module-trip/src/main/java/com/example/module_trip/account/AccountService.java
  module-trip/src/main/java/com/example/module_trip/account/AccountType.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRequestDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalResponseDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: bug, enhancement

#40 [Fix/#31-refactor-transaction] 송금하기 리팩토링
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionDTO.java
Labels: bug, enhancement

#43 [Feat/#41 create error]
  module-exchange/src/main/java/com/example/module_exchange/ModuleExchangeApplication.java
  module-utility/src/main/java/com/example/module_utility/response/GlobalExceptionHandler.java
  module-utility/src/main/java/com/example/module_utility/response/Response.java
Labels: enhancement

#46 [Fix/#8-exchange-dto] 환전하기 dto 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
Labels: bug

#52 [Feat/#8-trip-by-account] 계좌 id로 여행 목표 가져오기
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRepository.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: enhancement

#51 Feat/#50 jenkins cicd
  Jenkinsfile
  docker-compose.yml
  gateway-service/Dockerfile
  gateway-service/src/main/resources/application.yml
  module-alarm/Dockerfile
  module-exchange/Dockerfile
  module-member/Dockerfile
  module-member/src/main/java/com/example/module_member/user/UserController.java
  module-trip/Dockerfile
Labels: enhancement

#55 [Fix/#8-modfiy-tripcontroller] 중복 api 하나로 통합
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
Labels: bug

#56 [hotfix] local 개발을 위한 yml 임시 설정
  gateway-service/src/main/resources/application-docker.yml
  gateway-service/src/main/resources/application.yml
  module-alarm/src/main/resources/application.yml
  module-exchange/src/main/resources/application.yml
  module-member/src/main/resources/application.yml
  module-trip/src/main/resources/application.yml
Labels: bug

#59 [Feat/#31 description default] username으로 유저 받아오기
  gateway-service/src/main/resources/application.yml
  module-member/src/main/java/com/example/module_member/dto/UserResponseDto.java
  module-member/src/main/java/com/example/module_member/user/UserController.java
  module-member/src/main/java/com/example/module_member/user/UserService.java
Labels: enhancement

#64 [Fix/#31-order-desc] 송금일 기준 내림차순 정렬
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionHistoryRepository.java
Labels: bug, enhancement

#65 [Feat/#63 currency list] 유저의 목표별 특정 통화 보유량 조회
  module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyRepository.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/WalletResponseDTO.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/stockList/StockController.java
  module-member/src/main/java/com/example/module_member/dto/UserResponseDto.java
  module-trip/src/main/java/com/example/module_trip/account/AccountController.java
Labels: enhancement

#66 [Chore/#41 set response] 응답 형식 통일
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmController.java
  module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
  module-exchange/src/main/java/com/example/module_exchange/clients/MemberClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/ExchangeRateController.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/orderBook/OrderBookController.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/stockList/StockController.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/usOrderBooK/USOrderBookController.java
  module-trip/src/main/java/com/example/module_trip/account/AccountController.java
Labels: enhancement

#72 Feat/#50 cicd
  Jenkinsfile
  docker-compose.yml
  gateway-service/src/main/resources/application.yml
  module-alarm/src/main/resources/application.yml
  module-exchange/src/main/resources/application.yml
  module-member/src/main/resources/application.yml
  module-trip/src/main/resources/application.yml
Labels: enhancement

#75 [Fix/#31-refactor] 환전/송금 transactional 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
Labels: enhancement

#81 [Feat/#80 exchange batch] 타 목표와 함께 환전하기 api
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeBatchDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeHistory.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeType.java
Labels: enhancement

#83 [Fix/#31-transaction-basic] 입출금 내역 조회 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionHistoryRepository.java
Labels: bug, enhancement

#87 [fix/#82-modify-dto] history response DTO 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionHistoryResponseDTO.java
Labels: bug

#89 [fix/#8-modify-dto] 송금하기 dto 수정 및 description 로직 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionDTO.java
Labels: bug, enhancement

#94 [Feat/#93 send sms] sms 전송 api
  build.gradle
  module-member/src/main/java/com/example/module_member/sms/SmsController.java
  module-member/src/main/java/com/example/module_member/sms/SmsService.java
Labels: enhancement

#95 feat: Implement login status API(#90)
  module-member/src/main/java/com/example/module_member/user/UserController.java
Labels: enhancement

#96 [Feat/#93 check code] 번호 인증 api 구현
  build.gradle
  gateway-service/src/main/java/com/example/gateway_service/filter/JwtAuthFilter.java
  module-member/src/main/java/com/example/module_member/dto/CheckRequestDTO.java
  module-member/src/main/java/com/example/module_member/dto/SmsSendRequestDTO.java
  module-member/src/main/java/com/example/module_member/sms/RedisConfig.java
  module-member/src/main/java/com/example/module_member/sms/RestTemplateConfig.java
  module-member/src/main/java/com/example/module_member/sms/SmsController.java
  module-member/src/main/java/com/example/module_member/sms/SmsService.java
  module-member/src/main/resources/application-local.yml
  module-utility/src/main/java/com/example/module_utility/response/GlobalExceptionHandler.java
  module-utility/src/main/java/com/example/module_utility/response/InvalidVerificationCodeException.java
Labels: enhancement

#105 feat: implement userInfo API(#90)
  module-member/src/main/java/com/example/module_member/dto/SignUpRequestDto.java
  module-member/src/main/java/com/example/module_member/dto/UserInfoResponseDTO.java
  module-member/src/main/java/com/example/module_member/user/User.java
  module-member/src/main/java/com/example/module_member/user/UserController.java
  module-member/src/main/java/com/example/module_member/user/UserRepository.java
  module-member/src/main/java/com/example/module_member/user/UserService.java
Labels: enhancement

#107 [Feat/#104 rate alarm] 최저 환율 알림 트리거 로직 생성
  build.gradle
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRequestDTO.java
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
  module-alarm/src/main/java/com/example/module_alarm/fcm/FcmController.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/exchangeRateChart/ExchangeRateChartService.java
  module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/exchangeRateChart/ExchangeRateScheduler.java
Labels: enhancement

#108 "hotfix : modify user to username in header"
  module-exchange/src/main/java/com/example/module_exchange/clients/MemberClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-member/src/main/java/com/example/module_member/user/UserController.java
Labels: bug

#109 fix : add account id in return dto(#79)
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/AccountListDTO.java
Labels: bug, enhancement

#119 [Feat/#104 goal success] 목표 도달 알림 / 평가 손익 업데이트
  build.gradle
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRequestDTO.java
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
  module-exchange/src/test/java/com/example/module_exchange/learning/JsonNodeTest.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoal.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalProfitUpdateDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalUpdateDTO.java
Labels: enhancement

#121 Feat/#120 my trip
  module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrency.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyRepository.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyTotalDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/TripExchangeCurrencyDTO.java
  module-trip/src/main/java/com/example/module_trip/account/AccountController.java
  module-trip/src/main/java/com/example/module_trip/account/AccountRepository.java
  module-trip/src/main/java/com/example/module_trip/account/AccountService.java
  module-trip/src/main/java/com/example/module_trip/account/NormalAccountDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoal.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalListResponseDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRepository.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: enhancement

#130 [Feat/#104 goal half] 목표 기간 대비 목표 달성 50% 미만 알림
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmType.java
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: enhancement

#131 fix my trip api(#120)
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyTotalDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/TripExchangeCurrencyDTO.java
Labels: enhancement

#137 [Feat/#132 transfer goal] 목표 즉시 매도/환전
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeGoalDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeGoalListDTO.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeDTO.java
Labels: enhancement

#138 edit trip goal detail api(#135)
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/TripGoalDetailDTO.java
Labels: enhancement

#141 "fix : modify calculate rate & toAmount logic(#132)"
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
Labels: bug

#145 [Feat/#144-similar-trip] 유사한 trip goal id 목록 불러오기
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRepository.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: enhancement

#146 [Feat/#144-ranking] 포트폴리오 랭킹 갱신 및 조회
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/TripRankingDTO.java
Labels: enhancement

#149 [Feat/#104 goal finish] 목표 기간 만료 알림 트리거
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: enhancement

#152 "hotfix" 이후 커밋 복원
  Jenkinsfile
  build.gradle
  eureka-server/src/main/resources/application.yml
  gateway-service/src/main/resources/application-local.yml
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
  module-alarm/src/main/resources/application-local.yml
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: bug

#156 [feat : set firebase key in yml] fcm 키 루트 설정
  module-alarm/src/main/java/com/example/module_alarm/fcm/FcmService.java
  module-alarm/src/main/resources/application-local.yml
  module-alarm/src/main/resources/application.yml
Labels: enhancement

#165 [Fix/#7 request dto] fcm 토큰 저장 수정
  module-alarm/src/main/java/com/example/module_alarm/fcm/FcmController.java
  module-alarm/src/main/java/com/example/module_alarm/fcm/FcmTokenDTO.java
Labels: bug, enhancement

#173 [Fix/#104 alarm] 알림 request dto 수정
  minjibabo.txt
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRequestDTO.java
  module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
  module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
  module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
Labels: bug, enhancement

#189 [fix/#132-exchange-rate] 환율 계산 수정
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
Labels: bug, enhancement

#194 [Fix/open feign] account client 제거 및 trip client로 병합
  module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
  module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
Labels: bug

#196 [fix/open-feign] 각 모듈 별 application name 형식 통일
  gateway-service/src/main/resources/application-local.yml
  module-alarm/src/main/resources/application-local.yml
  module-exchange/src/main/resources/application-local.yml
  module-member/src/main/resources/application-local.yml
  module-trip/src/main/resources/application-local.yml
Labels: bug

#202 [Feat/#197-exchangecurrency] exchange currency api 추가
  module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
  module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
Labels: enhancement
